services:
  ollama:
    image: ollama/ollama
    volumes:
      - ./ollama-models:/root/.ollama
    ports:
      - "11434:11434"

  web:
    image: nginx:alpine
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - "3001:80"