local-deepseek/
├── docker-compose.yml
├── netlify.toml
├── package.json
└── web
    ├── index.html
    ├── ollama.js
    └── style.css

[build]
  command = "npm run build"
  publish = "build"
  base = "/"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  command = "npm start"
  targetPort = 3001
  port = 8888
  publish = "web"
  autoLaunch = false