[build]
  base = "/"
  command = "npm run build"
  publish = "build"

[dev]
  framework = "create-react-app"
  targetPort = 3001

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200